# Makefile
#
# Requires:
#	- limactl
#
# Usage:
#	$ [PROGRESS=1] [LOG_LEVEL=info|debug|warn] make {edge|mini|...}
#
VM_NAME :=
_VM_USER := lima

# Lima default is 'info' but it's too verbose. Let's do our own default.
#
# Note: 'warn' means awefully quiet. Even when things go wrong, Lima (2.2.0) prefers to list them as INFO.
#
LOG_LEVEL ?= warn
_LIMACTL_FLAGS := --log-level $(LOG_LEVEL)

ifeq ($(PROGRESS), 1)
  _LIMACTL_FLAGS += --progress
endif

_MAKEFILE := $(lastword $(MAKEFILE_LIST))

# This is how you'd figure any path.
#_MAKE_PATH := $(patsubst %/,%,$(dir $(abspath $($(lastword $(MAKEFILE_LIST))))))

# A file generated by 'limactl start'. Can be used for ssh'ing into a running VM instance.
# <<
#	Host lima-edge-vm
#	  IdentityFile "/Users/xxx/.lima/_config/user"
#	  ...
#	  Port 49925
# <<
#
_VM_SSH_CONFIG := ~/.lima/$(VM_NAME)/ssh.config

# Makefile note: defining multi-line blocks with 'define' + 'export'.
define SSH_CONFIG_BLOCK
Match all
Include $(_VM_SSH_CONFIG)
endef
export SSH_CONFIG_BLOCK

# Contents to '{vm name}/custom.mounts.list' if such does not exist.
define CUSTOM_MOUNTS_TEMPLATE
# Folders you'd like to see within the VM's '/home/lima/'.
#
#~/Git/Some			# --> /home/lima/Some
#/Users/you/Other	# --> /home/lima/Other
endef
export CUSTOM_MOUNTS_TEMPLATE

# Template that does not have mounts
_ORIG_YAML:=$(VM_NAME)/project.yaml

# Actual YAML; includes mounts
_TMP_YAML:=tmp/$(VM_NAME)-custom.yaml

_CUSTOM_MOUNTS:=$(VM_NAME)/custom.mounts.list

#---
# Shorthands
#
edge mini:
	@$(MAKE) vm VM_NAME=$@-vm

#---
# Note: Also creates '_VM_SSH_CONFIG', but we cannot easily express that in 'make' < v4 syntax. Does not matter, trust
#		that it gets done!
#
vm: $(_TMP_YAML) | limactl ssh_exists no_prior_vm
	limactl start --name=$(VM_NAME) -y $(_LIMACTL_FLAGS) -- $(_TMP_YAML)

	@# Pass only with a spotless provisioning!
	@limactl shell $(VM_NAME) cloud-init status --wait > /dev/null || \
	  { \
	    echo -e "\nJust a clip:\n---"; \
	    limactl shell edge-vm sudo cat /var/log/cloud-init-output.log | grep -E "WARNING|ERROR"; \
	    echo "---"; \
	    printf >&2 "\n❗ ERROR: Some provisioning step(s) failed! Check logs with: limactl shell $(VM_NAME) sudo cat /var/log/cloud-init-output.log\n"; \
	    false; \
	}

	@test -f $(_VM_SSH_CONFIG) || \
	  	{ printf >&2 "❗ERROR: '$(_VM_SSH_CONFIG)' was not produced.\n"; false; }

	@# Concat to '~/.ssh/config' so one can directly 'ssh' to the VM. Important for IntelliJ Remote Development.
	@# tbd. THIS MIGHT NOT BE NEEDED; check 'loadDotSSHPubKeys' in the YAML.
	@grep -q "Include ~/.lima/$(VM_NAME)/ssh.config" ~/.ssh/config || ( \
    	echo "$$SSH_CONFIG_BLOCK" >> ~/.ssh/config \
    )
	@grep -q "Include ~/.lima/$(VM_NAME)/ssh.config" ~/.ssh/config || \
    	{ printf >&2 "❗INTERNAL ERROR: didn't modify '~/.ssh/config' properly!\n"; false; }

	@# Dive right in!
	@limactl shell $(VM_NAME)

# Mod a copy:
#	- remove 'mounts: null' (if any)
#	- appends mounts from '$(_CUSTOM_MOUNTS)'
#
$(_TMP_YAML): $(_ORIG_YAML) $(_CUSTOM_MOUNTS) $(_MAKEFILE) sh/mounts-filter.sh
	@sh/mounts-filter.sh $(_CUSTOM_MOUNTS) < $(_ORIG_YAML) \
	  > $@

# Create a template if not there (hints the user that they could use one).
#
$(_CUSTOM_MOUNTS):
	@echo "$$CUSTOM_MOUNTS_TEMPLATE" >> $@

# Demanded if 'VM_NAME' were empty
/project.yaml:
	$(error Missing 'VM_NAME', example: make $@ VM_NAME=edge-vm)

limactl:
	@which $@ >/dev/null || \
	  { printf >&2 "❗ ERROR: '$@' not found on PATH.\n"; false; }

# We are okay creating '~/.ssh/config' but not the '~/.ssh' folder itself (access rights etc.).
ssh_exists:
	@[ -d ~/.ssh ] || \
	  { printf >&2 "❗ ERROR: Expected '~/.ssh' to exist.\n"; false; }

# Test that '$(VM_NAME)' does not already exist.
# Lime would give an error if it does, but that error looks ugly. ("FATA[0000] ...")
no_prior_vm:
	@if limactl list $(VM_NAME) > /dev/null 2>&1; then \
	  printf >&2 "❗ '$(VM_NAME)' already exists; you need to either 'limactl edit $(VM_NAME)' or 'limactl delete -f $(VM_NAME)'.\n"; \
	  false; \
	fi

#---
echo:
	@echo $(_LIMACTL_FLAGS)

.PHONY: edge mini vm limactl ssh_exists no_prior_vm echo
