# Makefile
#
# Requires:
#	- limactl
#
# Usage:
#	$ make {edge|mini|...}
#	$ make vm VM_NAME={...}-vm
#
VM_NAME :=
_VM_USER := lima

# A file generated by 'limactl start'. Can be used for ssh'ing into a running VM instance.
# <<
#	Host lima-edge-vm
#	  IdentityFile "/Users/xxx/.lima/_config/user"
#	  ...
#	  Port 49925
# <<
#
_VM_SSH_CONFIG := ~/.lima/$(VM_NAME)/ssh.config

# Makefile note: defining multi-line blocks with 'define' + 'export'.
define SSH_CONFIG_BLOCK
Match all
Include $(_VM_SSH_CONFIG)
endef
export SSH_CONFIG_BLOCK

_YAML:=$(VM_NAME)/project.yaml
	# {xxx}-vm/project.yaml

# Shorthands
edge mini:
	@$(MAKE) vm VM_NAME=$@-vm

# Note: Also creates '_VM_SSH_CONFIG', but we cannot easily express that in 'make' < v4 syntax. Does not matter,
#		trust that it gets done!
#
vm: $(_YAML) | limactl ssh_exists
ifndef VM_NAME
	$(error Missing 'VM_NAME', example: make $@ VM_NAME=edge-vm)
endif
	@# Note: To DEBUG, add '--progress'
	@limactl start --name=$(VM_NAME) --mount-none -y -- $<

	@test -f $(_VM_SSH_CONFIG) || \
	  	{ printf >&2 "❗ERROR: '$(_VM_SSH_CONFIG)' was not produced.\n"; false; }

	@# Concat to '~/.ssh/config' so one can directly 'ssh' to the VM. Important for IntelliJ Remote Development.
	@grep -q "Include ~/.lima/$(VM_NAME)/ssh.config" ~/.ssh/config || ( \
    	echo "$$SSH_CONFIG_BLOCK" >> ~/.ssh/config \
    )
	@grep -q "Include ~/.lima/$(VM_NAME)/ssh.config" ~/.ssh/config || \
    	{ printf >&2 "❗INTERNAL ERROR: didn't modify '~/.ssh/config' properly!\n"; false; }

	@# So you can mount the folders
	@limactl stop $(VM_NAME)

limactl:
	@which limactl >/dev/null || \
	  { printf >&2 "❗ ERROR: '$@' not found on PATH.\n"; false; }

# We are okay creating '~/.ssh/config' but not the '~/.ssh' folder itself (access rights etc.).
ssh_exists:
	@[ -d ~/.ssh ] || \
	  { printf >&2 "❗ ERROR: Expected '~/.ssh' to exist.\n"; false; }

#---
echo:
	@echo xxx

.PHONY: vm limactl ssh_exists echo
