# yaml-language-server: $schema=none
#
# Note: There does not seem to be a schema available for Lima 2.2.0.
#     Until there is one(?), see -> https://github.com/lima-vm/lima/blob/master/templates/default.yaml
#
minimumLimaVersion: 2.0.0

# macOS defaults ('vz', 'virtiofs'); for other OS'es, just comment them out.
vmType: "vz"
mountType: "virtiofs"

# See: https://github.com/lima-vm/lima/blob/master/templates/ubuntu-26.04.yaml
#     - https://github.com/lima-vm/lima/blob/master/templates/_images/ubuntu-26.04.yaml
#     - https://github.com/lima-vm/lima/blob/master/templates/_default/mounts.yaml
#
#   NOTE: Omitting the 'mounts' (which we don't use) causes the _prompt_ of the VM to lose colour, and just... be awkward.
#
base: "template:ubuntu-lts"

# System Resources
#
cpus: 4
memory: "8GiB"
  # 8GB of RAM needed for Remote Development
disk: "20GiB"

mountInotify: true

user:
  name: "lima"
  home: "/home/{{.User}}"
    # Lima defaults to '/home/{{.User}}.guest', we don't need the host/client disambiguation.

# EDIT THESE AT THE END OF THE FILE, replacing 'mounts: none'
#
#mounts:
#  - location: "/Users/xxx/Git/Some"
#    mountPoint: "/home/lima/Some"
#    writable: true

ssh:
  # Note: Variate the port per-project if you need to use multiple Remote Development sessions, simultaneously.
  localPort: 49924

portForwards:
  # Silence (some) warnings, when creating the VM
  # Note: Rules read from top down (order matters)
  - guestIP: "0.0.0.0"
    proto: "udp"
    ignore: true
  - guestPort: 323
    proto: "any"
    ignore: true
  # Application ports, plus Lima's own ssh
  - guestPortRange: [1024, 65535]
    proto: "tcp"

# Install:
#   - PodMan
#   - Vitest (for running tests)
#
#   Note:
#     Deployments will also need 'cloudflared' (Cloudflare tunnel) to be set up, but it's intentionally not installed
#     here. You don't need it for development. See 'Tunnel'.
#
# Template variables (Lima docs and a test run):
#   {{.Home}}   /home/lima
#   {{.Name}}   mini-vm
#   {{.Hostname}} lima-mini-vm
#   {{.UID}}    502
#   {{.User}}   lima
#   {{.Param.Key}} <no value>
#
# NOTE:
#   'DEBIAN_FRONTEND=noninteractive' matters (for 'system' provisioning). Keep it.
#
provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eu -o pipefail
      export DEBIAN_FRONTEND=noninteractive
      
      apt-get update
      apt install -y curl git pkg-config libssl-dev

      #🟡 Podman
      #   ❗️NOTE: THIS IS PODMAN 5.7 FOR NOW (6.0.2 not available via 'apt'; 31-Aug-26, 29-Jul-26)
      #apt install -y podman podman-compose

      #🟡 Node.js via NodeSource
      curl -fsSL https://deb.nodesource.com/setup_26.x | bash -
      apt install -y nodejs
      
      # 🟡Optimize 'node_modules' speed
      # Note: could do this in the 'mounts' section, once we in general can do mounts here... (the lack of '--mountOnly' in YAML)
      touch ~/system.2
      grep -q "tmpfs_abc" /etc/fstab || (
        touch ~/system.3
        _MP=${_PROJ_HOST_PATH}/node_modules
        install -d $_MP
        _GID=$(id -g {{.User}})
        touch ~/system.4

        cat >> /etc/fstab << ABC
        
      # Optimize 'node_modules' within the VM
      tmpfs_abc $_MP tmpfs user,noauto,exec,rw,size=800m,uid={{.UID}},gid=$_GID 0 0
      ABC
 
        systemctl daemon-reload
        mount $_MP
      )
      
      # 🟡Just
      apt install -y just

      # DEBUG
      touch {{.Home}}/system.done

  - mode: user
    script: |
      #!/bin/bash
      set -eu -o pipefail

      # Check that 'system' provisioning succeeded
      test -f ~/system.done

      #🔵 rustup (Rust, Cargo) + WASM tools
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- \
        --default-toolchain nightly -y --profile minimal

      . ~/.cargo/env
      
      install -d ~/.local/share/bash-completion/completions
      rustup completions bash       > ~/.local/share/bash-completion/completions/rustup
      rustup completions bash cargo > ~/.local/share/bash-completion/completions/cargo

      cargo install wasm-pack

      #🔵 A common, VM-internal 'target' (less sharing; better performance)
      #   NOTE: Do not use '/tmp/target' - it's mounted as a memory disk in Ubuntu template and will exhaust.
      install -d ~/target
      
      CONFIG_TOML=~/.cargo/config.toml
      [ ! -f "$CONFIG_TOML" ] || { printf >&2 "${CONFIG_TOML} already exists"; false; }
  
      cat >> $CONFIG_TOML <<EOF1
      [build]
      target-dir = "{{.Home}}/target"
      EOF1
  
      #🔵 Enable 'npm -g' without 'sudo'
      install -d "$HOME/.npm-packages"
      npm config set prefix "$HOME/.npm-packages"

      cat >> ~/.bashrc << 'EOF'

      # npm installed to a custom location
      #
      export PATH="$PATH:$HOME/.npm-packages/bin"
      
      EOF
      
      # DEBUG
      touch ~/user.done
