# yaml-language-server: $schema=none
#
# Note: There is no schema available for Lima 2.2.0.
#     Until there is one (?), see -> https://github.com/lima-vm/lima/blob/master/templates/default.yaml
#
minimumLimaVersion: 2.2.0

# macOS defaults ('vz', 'virtiofs'); for other OS'es, just comment them out.
vmType: "vz"
mountType: "virtiofs"

# Instead of a template, we use a specific image. This is vital for embedded development (USB/IP client) dependencies
# (linux-tools-generic, vhci-hcd).
#
# According to 'google.ai', it's difficult to add the kernel extensions afterwards.
#
images:
  - location: "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-arm64.img"
    arch: "aarch64"

  # NOTE: Intel NOT TESTED
  - location: "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img"
    arch: "x86_64"

# System Resources
#
cpus: 4
memory: "8GiB"
  # 8GB of RAM needed for Remote Development
disk: "40GiB"
  # 20GB falls short with Remote Development and ESP-IDF Rust projects
  # If you use multiple ESP-IDF versions (e.g. 5.5.5, 6.0), each takes ~6..8 GB (~/.espressif).

# Marked as: "EXPERIMENTAL" (2.2.0)
#
# DISABLED because: We might not actually need it (unlike in, say, web development); there have been some conflict
#   dialogs in Rust Rover IDE (memory vs. disk content). #undecided
#mountInotify: true

user:
  name: "lima"
  home: "/home/{{.User}}"
    # Lima defaults to '/home/{{.User}}.guest', we don't need the host/client disambiguation.

param:
  # Expects a certain name for the Raspberry Pi. Override this by '--param PROBE_RS_REMOTE=...'.
  PROBE_RS_REMOTE: probe-rs@rpi.local

  # Where provisioning sentinel files reside
  #
  # Requirements for the path:
  #   - survives restarts ('/tmp/' does not)
  #   - also the 'lima' user can write to (if we add it to the 'wheel' group, it could write to '/var/...').
  #
  # NOTE: Expanding Lima (2.3.0-beta.0) parameters does not seem to be recursive: '{{.Home}}' cannot be used.
  #
  #STL_PATH: "{{.Home}}/.lima-provision"
  STL_PATH: "/home/lima/.lima-provision"

ssh:
  # Note: Variate the port per-project if you need to use multiple Remote Development sessions, simultaneously.
  localPort: 49925
  # Rust Rover Remote Development needs that the VM is approachable only using the '~/.ssh/config'.
  #loadDotSSHPubKeys: true
  #   tbd. Does this eliminate the need to edit the '~/.ssh/config'?

portForwards:
  # Silence (some) warnings, when creating the VM
  # Note: Rules read from top down (order matters)
  - guestIP: "0.0.0.0"
    proto: "udp"
    ignore: true
  - guestPort: 323
    proto: "any"
    ignore: true
  # Application ports, plus Lima's own ssh
  - guestPortRange: [1024, 65535]
    proto: "tcp"

#---
# Provisioning scripts
#
# Template variables (Lima docs and a test run):
#   {{.Home}}   /home/lima
#   {{.Name}}   edge-vm
#   {{.Hostname}} lima-edge-vm
#   {{.UID}}    502
#   {{.User}}   lima
#   {{.Param.Key}} "<no value>" if empty
#
# Environment variables:
#   PARAM_{Key}
#
# ⭐️READ ME!!
#     Provisioning happens *every time* a VM is stopped, restarted. This is to allow edits of the config to reach the VM
#     (author's guess), but for our needs a _one time_ initialization is most useful and performant.
#
#     The documentation does ask the scripts to be idempotent. We go further, using sentinel files to see whether they
#     ever succeeded (and skipping if did). You can *easily* tweak this by incrementing the "version" counter part of
#     the sentinel name (i.e. if you make an edit, increment the "version"; no need to recreate the VM!).
#
# NOTES:
#   - 'DEBIAN_FRONTEND=noninteractive' matters (for 'system' provisioning). Keep it.
#   - 'apt-get update' is not needed, unless we change the sources (cloudinit has run it for a new instance).
#
provision:
  # Tool for the provisioning steps to log their progress.
  #
  # NOTE: THIS DOES NOT WORK. The idea was to bring progress messages to the host, so they are seen while creating/
  #     starting the VM. This seems to rub Lima VM the wrong way (i.e. not yet possible; Lima 2.2.0).
  #
  #     Doing so would:
  #       - give transparency to what's happening
  #       - help avoid wasting time (e.g. duplication of steps; spotting overly time-taking steps..)
  #
  #     The author decides to keep the mechanism here. Perhaps Lima itself will provide something akin (just dumping
  #     the "name" of a provisioning step (could be an optional field?), or "system.{1..}", "user.{1..}" would already help).
  #
  # NOTE: Unlike for modes 'system', 'user', Lima (2.2.0) DOES NOT EXPAND TEMPLATE STRINGS within 'mode: data'.
  #     Would be welcome if it did...
  #
  # ALSO WELCOME: Way to create a folder (not just a file) from 'mode: data'. Would use that for '{.Param.STL_PATH}'. #lima
  #
  - mode: data
    path: /usr/local/bin/log-to-host
    permissions: 755
    #x-name: Tool for showing progress
    content: |
      #!/bin/bash
      # Attempt to write directly to host 'limactl' output. THIS DOES NOT WORK.
      #echo "[PROVISION] $*" > /dev/hvc0 2>/dev/null || true
      echo "[PROVISION] $*" >&2
      #echo "[PROVISION] $*" > {{.Param.STL_PATH}}/log  # Templates NOT EXPANDED within 'mode: data' #lima

  # Prepare provision directory
  - mode: system
    #x-name: Prepare provision directory
    script: |
      #!/bin/bash
      set -eux -o pipefail
      
      STL_PATH="{{.Param.STL_PATH}}"
      mkdir -p "$STL_PATH"
      chown {{.User}} "$STL_PATH"
      
      #|# Allow also 'mode: user' steps to write to '/dev/...'.
      #|usermod -aG dialout,tty {{.User}}
      #|
      #|# udev rule, to "provide 'tty' group access to 'hvc0' device" (google.ai); not sure whether necessary..? tbd.
      #|echo 'KERNEL=="hvc0", GROUP="tty", MODE="0660"' > /etc/udev/rules.d/99-hvc0-permissions.rules
      #|udevadm control --reload-rules
      #|udevadm trigger
      
      log-to-host "Provisioning receipts at: $STL_PATH"
      touch {{.Home}}/DONE.1

  # Prepare user space
  #   - make sure colored command line prompt is there, by copying templates from '/etc/skel/.bashrc'
  #
  - mode: user
    #x-name: Prepare user space
    script: |
      #!/bin/bash
      set -eux -o pipefail

      SENTINEL="{{.Param.STL_PATH}}/bashrc_comment.1.done"
      if [ -f "$SENTINEL" ]; then
        log-to-host "bashrc comment (skipped)"
        exit 0
      fi
      log-to-host "bashrc comment ..."

      cp /etc/skel/.bashrc ~/
      cp /etc/skel/.profile ~/
        
      # Leave a comment at the end of '.bashrc' - later steps append to that.
      cat >> ~/.bashrc <<EOF

      # Added at VM preparation:
      EOF
      
      touch "$SENTINEL"

  # ESP-IDF + bindgen dependencies
  - mode: system
    #x-name: ESP-IDF + bindgen dependencies
    script: |
      #!/bin/bash
      set -eux -o pipefail
      export DEBIAN_FRONTEND=noninteractive

      # DEV note: Increment '.{1..n}', to force rerun on next 'limactl start', without needing to recreate the VM.
      #
      SENTINEL="{{.Param.STL_PATH}}/deps.1.done"
      if [ -f "$SENTINEL" ]; then
        log-to-host "apt install (skipped)"
        exit 0
      fi
      log-to-host "apt install ..."

      # 'apt-get update' can be omitted
      apt-get install -y curl git pkg-config libssl-dev python3 python3-venv cmake build-essential clang make

      touch "$SENTINEL"

  # Rust and Cargo (general)
  - mode: user
    #x-name: Rust and Cargo (general)
    script: |
      #!/bin/bash
      set -eux -o pipefail

      SENTINEL="{{.Param.STL_PATH}}/rust_and_cargo.1.done"
      if [ -f "$SENTINEL" ]; then
        log-to-host "Rust and Cargo (skipped)"
        exit 0
      fi
      log-to-host "Rust and Cargo ..."

      #🔵 rustup (Rust, Cargo)
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- \
        --default-toolchain stable -y --profile minimal

      . ~/.cargo/env
      
      install -d ~/.local/share/bash-completion/completions
      rustup completions bash       > ~/.local/share/bash-completion/completions/rustup
      rustup completions bash cargo > ~/.local/share/bash-completion/completions/cargo

      #🔵 A common, VM-internal 'target' (less sharing; better performance)
      #   NOTE: Do not use '/tmp/target' - it's mounted as a memory disk in Ubuntu template and could fill up.
      install -d ~/target

      # Allow '~/.cargo/config.toml' to exist (and override it). This would happen if we're re-running the step, 
      # after a sentinel version pump.
      #
      CONFIG_TOML=~/.cargo/config.toml
      [ ! -f "$CONFIG_TOML" ] || { printf >&2 "WARN: ${CONFIG_TOML} already exists (will be replaced)"; }
  
      cat > $CONFIG_TOML <<EOF1
      [build]
      target-dir = "{{.Home}}/target"
      EOF1

      touch "$SENTINEL"

  # Rust and Cargo (ESP32-C6 specific)
  - mode: user
    #x-name: Rust and Cargo (ESP32-C6 specific)
    script: |
      #!/bin/bash
      set -eux -o pipefail

      SENTINEL="{{.Param.STL_PATH}}/rust_esp32_c6.1.done"
      if [ -f "$SENTINEL" ]; then
        log-to-host "Rust support for ESP32-C6 (skipped)"
        exit 0
      fi
      log-to-host "Rust support for ESP32-C6 ..."

      #🔵 ESP32-C6 target
      rustup target add riscv32imac-unknown-none-elf

      #🔵 CLI tools ('ldproxy' needed for ESP-IDF builds with 'global')
      cargo install --locked ldproxy

      touch "$SENTINEL"

  # Client side support for 'espflash' and 'probe-rs' remoting.
  #
  # To use this, edit the 'param.PROBE_RS_REMOTE' entry above, to point to your device.
  #
  - mode: user
    #x-name: 'espflash' and 'probe-rs' remoting (clients)
    script: |
      #!/bin/bash
      set -eux -o pipefail
      
      # Skip if not configured
      #
      # Note:
      #   - {{.Param.xxx}} gives "<no value>" when not defined.
      #   - ${PARAM_xxx} gives "" when not defined, so test that first. If exists, can use '{{.Param.xxx}}'.
      #
      [ -z ${PARAM_PROBE_RS_REMOTE} ] && { \
        log-to-host "espflash and probe-rs remoting: not configured"; \
        printf >&2 "probe-rs/espflash remoting disabled"; exit 0; \
      }

      SENTINEL="{{.Param.STL_PATH}}/remoting.1.done"
      if [ -f "$SENTINEL" ]; then
        log-to-host "espflash and probe-rs remoting to: '{{.Param.PROBE_RS_REMOTE}}' (skipped)"
        exit 0
      fi
      log-to-host "espflash and probe-rs remoting to: '{{.Param.PROBE_RS_REMOTE}}' ..."

      #🔵 Set in '.bashrc'
      cat >> ~/.bashrc <<EOF1
      export PROBE_RS_REMOTE={{.Param.PROBE_RS_REMOTE}}
      EOF1
      
      #🔵 Set up '~/bin' if not already there
      [ -d ~/bin ] || { \
        install -d ~/bin; \
        echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc; \
      }

      curl -fsSL -o ~/bin/probe-rs-remote.sh https://raw.githubusercontent.com/finalyards-org/probe-rs-remote/refs/heads/main/sh/probe-rs-remote.sh
      chmod a+x ~/bin/probe-rs-remote.sh

      curl -fsSL -o ~/bin/espflash-remote.sh https://raw.githubusercontent.com/finalyards-org/probe-rs-remote/refs/heads/main/sh/espflash-remote.sh
      chmod a+x ~/bin/espflash-remote.sh

      (cd ~/bin && ln -sf probe-rs-remote.sh probe-rs)
      (cd ~/bin && ln -sf espflash-remote.sh espflash)
      
      # !! Disabled, since this isn't strictly necessary and the EARLIER VERSION WITHOUT NAMING 'id_rsa' MAY HAVE
      #       WORKED BETTER! tbd.
      #
      #|# Create an ssh key for later (manual) pairing.
      #|#
      #|# After this, one can avoid being asked pw's, by:
      #|#   <<
      #|#     ssh-copy-id $PROBE_RS_REMOTE
      #|#   <<
      #|if [ ! -f ~/.ssh/id_rsa ]; then
      #|  ssh-keygen -t rsa -C "for espflash remoting" -q -N "" -f ~/.ssh/id_rsa
      #|fi

      (grep -q "WarnWeakCrypto no-pq-kex" ~/.ssh/config 2>/dev/null) || \
        cat >> ~/.ssh/config <<EOF3
      # Block quantum warning on using 'espflash' remotely
      Match host ${PARAM_PROBE_RS_REMOTE#*@}
        WarnWeakCrypto no-pq-kex
      EOF3

      touch "$SENTINEL"

  # Let the host resolve 'rpi.local' for remoted probe-rs / espflash use. It does have access to mDNS; we don't.
  #
  # Note: Lighter than doing this by using a bridging network adapter (the author's opinion).
  #
  # TESTING:
  #   After this, 'resolvectl status' (within VM) should show
  #     - 'Link 2 (eth0)': 'DNS Domain: ~local'
  #
  - mode: system
    #x-name: DNS resolution for '.local' domain
    script: |
      #!/bin/bash
      set -eux -o pipefail

      SENTINEL="{{.Param.STL_PATH}}/local_domains.1.done"
      if [ -f "$SENTINEL" ]; then
        log-to-host "Enabling '.local' domains (skipped)"
        exit 0
      fi
      log-to-host "Enabling '.local' domains ..."

      [ -d /etc/netplan ] || { printf >&2 "No '/etc/netplan'; weird"; false; }

      FN=/etc/netplan/99-mdns-routing.yaml

      cat << 'EOF4' | tee $FN
      network:
        version: 2
        ethernets:
          eth0:
            dhcp4: true
            dhcp4-overrides:
              use-dns: true
            nameservers:
              search: [ "local" ]
      EOF4

      chmod 600 $FN
      netplan apply

      # Check that normal DNS still works
      #ping -c 1 rustup.sh
      
      touch "$SENTINEL"

  # DEBUG. Finish up.
  # Note: Lima VM first runs all 'mode: system' scripts, then all 'mode: user'. Sequentially, in order.
  #
  - mode: system
    script: |
      #!/bin/bash
      touch {{.Home}}/DEBUG.system.all.done

  - mode: user
    script: |
      #!/bin/bash
      touch ~/DEBUG.user.all.done
