# yaml-language-server: $schema=none
#
# Note: There does not seem to be a schema available for Lima 2.2.0.
#     Until there is one(?), see -> https://github.com/lima-vm/lima/blob/master/templates/default.yaml

#
# rust-embassy/project.yaml
#

#
# See: https://github.com/lima-vm/lima/blob/master/templates/ubuntu-26.04.yaml
#     - https://github.com/lima-vm/lima/blob/master/templates/_images/ubuntu-26.04.yaml
#     - https://github.com/lima-vm/lima/blob/master/templates/_default/mounts.yaml
#
#   NOTE: Omitting the 'mounts' (which we don't use) causes the _prompt_ of the VM to lose colour, and just... be awkward.
#
#base: "template:ubuntu-lts"
base: "template:_images/ubuntu-lts.yaml"

# System Resources
#
cpus: 4
memory: "8GiB"
  # 8GB of RAM needed for Remote Development
disk: "40GiB"
  # 20GB falls short with Remote Development and ESP-IDF Rust projects
  # If you use multiple ESP-IDF versions (e.g. 5.5.5, 6.0), each takes ~6..8 GB (~/.espressif).

# macOS defaults ('vz', 'virtiofs'); for other OS'es, just comment them out.
vmType: "vz"
mountType: "virtiofs"

mountInotify: true

user:
  name: "lima"
  home: "/home/{{.User}}"
    # Lima defaults to '/home/{{.User}}.guest', we don't need the host/client disambiguation.

# EDIT THESE AT THE END OF THE FILE, replacing 'mounts: none'
#
#mounts:
#  - location: "/Users/xxx/Git/Some"
#    mountPoint: "/home/lima/Some"
#    writable: true

ssh:
  # Note: Variate the port per-project if you need to use multiple Remote Development sessions, simultaneously.
  localPort: 49925

portForwards:
  # Silence (some) warnings, when creating the VM
  # Note: Rules read from top down (order matters)
  - guestIP: "0.0.0.0"
    proto: "udp"
    ignore: true
  - guestPort: 323
    proto: "any"
    ignore: true
  # Application ports, plus Lima's own ssh
  - guestPortRange: [1024, 65535]
    proto: "tcp"

# Template variables (Lima docs and a test run):
#   {{.Home}}   /home/lima
#   {{.Name}}   edge-vm
#   {{.Hostname}} lima-edge-vm
#   {{.UID}}    502
#   {{.User}}   lima
#   {{.Param.Key}} <no value>
#
# NOTE:
#   'DEBIAN_FRONTEND=noninteractive' matters (for 'system' provisioning). Keep it.
#
provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eu -o pipefail
      export DEBIAN_FRONTEND=noninteractive
      
      apt-get update
      apt install -y curl git pkg-config libssl-dev python3 python3-venv cmake \
        make \
        build-essential clang
  
      _PROJ_HOST_PATH=$(find /Users -type d -name "Den-edge")
      test -d $_PROJ_HOST_PATH

      # 🟡Misc
      apt install -y just jq
      # 🟡Convenience
      apt install -y tree

      # Signal to the 'user' mode installs (below) that we finished.
      touch {{.Home}}/system.done

  - mode: user
    script: |
      #!/bin/bash
      set -eu -o pipefail

      # Check that 'system' provisioning succeeded
      test -f ~/system.done

      #🔵 rustup (Rust, Cargo)
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- \
        --default-toolchain stable -y --profile minimal

      . ~/.cargo/env
      
      install -d ~/.local/share/bash-completion/completions
      rustup completions bash       > ~/.local/share/bash-completion/completions/rustup
      rustup completions bash cargo > ~/.local/share/bash-completion/completions/cargo

      #🔵 A common, VM-internal 'target' (less sharing; better performance)
      #   NOTE: Do not use '/tmp/target' - it's mounted as a memory disk in Ubuntu template and will exhaust.
      install -d ~/target
      
      CONFIG_TOML=~/.cargo/config.toml
      [ ! -f "$CONFIG_TOML" ] || { printf >&2 "${CONFIG_TOML} already exists"; false; }
  
      cat >> $CONFIG_TOML <<EOF1
      [build]
      target-dir = "{{.Home}}/target"
      EOF1

      #🔵 Project specific: ESP32-C6 target and tools for 'ezb-node'
      rustup target add riscv32imac-unknown-none-elf

      # Note: 'bindgen-cli' must come from 'cargo install', NOT 'apt'.
      cargo install --locked bindgen-cli
      cargo install --locked ldproxy

      #🔵 Optional: 'cargo cache -a' good for cleanup of git-cloned Cargo repos
      cargo install cargo-cache --locked

      #🔵 Set up 'espflash' remoting; -> https://github.com/finalyards-org/probe-rs-remote
      #   The user is expected to modify '~/.bashrc' and '~/.ssh/config' manually.
      #
      install -d ~/bin

      cat >> ~/.bashrc <<'EOF2'
      # 'probe-rs' and 'espflash' remotely
      export PROBE_RS_REMOTE=probe-rs@192.168.1.97  # EDIT THIS TO POINT TO YOUR DEVICE
      export PATH=$PATH:$HOME/bin
      EOF2

      curl -fsSL -o ~/bin/espflash-remote.sh https://raw.githubusercontent.com/finalyards-org/probe-rs-remote/refs/heads/main/sh/espflash-remote.sh
      chmod a+x ~/bin/espflash-remote.sh
  
      (cd ~/bin && ln -s espflash-remote.sh espflash )

      # Create an ssh key for later (manual) pairing.
      #
      # After this, one can avoid being asked pw's, by:
      #   <<
      #     ssh-copy-id probe-rs@192.168.1.xx
      #   <<
      ssh-keygen < /dev/zero > /dev/null \
        -t rsa -C "for 'espflash' remote" -q -N ""

      cat >> ~/.ssh/config <<'EOF3'
      # Block quantum warning on using 'espflash' remotely
      # v-- EDIT THE IP TO MATCH YOUR DEVICE!!
      Match host 192.168.1.97
        WarnWeakCrypto no-pq-kex
      EOF3

      # DEBUG
      touch ~/user.done
